{% set name = "rdflib-pyld-compat" %}
{% set python_min = "3.10" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdflib-pyld-compat-{{ version }}.tar.gz
  sha256: 40d353e0d75d50966d8c3b6dd948fe9801681636037087e9dd186fe35cd87831

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=65.0.0
  run:
    - python >={{ python_min }}
    - rdflib >=4.2.0
    - pyld
    - testfixtures

test:
  imports:
    - rdflib_pyld_compat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/zimeon/rdflib-pyld-compat
  summary: Conversion between rdflib and PyLD data formats for compatibility
  license: 'Apache-2.0'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marimeireles
    - joshmoore
